py_test(
    name = "test_xgrammar_backend",
    srcs = [
        "test_xgrammar_backend.py",
    ],
    data = [
        "//rtp_llm:sdk",
    ],
    deps = [
        "//rtp_llm:testlib",
    ],
    exec_properties = {"gpu": "H20"},
    tags = ["manual"],
)

py_test(
    name = "test_structural_tag",
    srcs = [
        "test_structural_tag.py",
    ],
    data = [
        "//rtp_llm:sdk",
    ],
    deps = [
        "//rtp_llm:testlib",
    ],
    exec_properties = {"gpu": "H20"},
    tags = ["manual"],
)

py_test(
    name = "test_reasoner_grammar_backend",
    srcs = [
        "test_reasoner_grammar_backend.py",
    ],
    data = [
        "//rtp_llm:sdk",
    ],
    deps = [
        "//rtp_llm:testlib",
    ],
    tags = ["manual"],
)

py_test(
    name = "test_grammar_cache",
    srcs = [
        "test_grammar_cache.py",
    ],
    data = [
        "//rtp_llm:sdk",
    ],
    deps = [
        "//rtp_llm:testlib",
    ],
    tags = ["manual"],
)

py_test(
    name = "test_grammar_batch_ops_draft",
    srcs = [
        "test_grammar_batch_ops_draft.py",
    ],
    data = [
        "//rtp_llm:sdk",
    ],
    deps = [
        "//rtp_llm:testlib",
    ],
    exec_properties = {"gpu": "H20"},
    tags = ["manual"],
)

py_test(
    name = "test_base_grammar_backend",
    srcs = [
        "test_base_grammar_backend.py",
    ],
    data = [
        "//rtp_llm:sdk",
    ],
    deps = [
        "//rtp_llm:testlib",
    ],
    tags = ["manual"],
)

py_test(
    name = "test_bitmask_ops",
    srcs = [
        "test_bitmask_ops.py",
    ],
    data = [
        "//rtp_llm:sdk",
    ],
    deps = [
        "//rtp_llm:testlib",
    ],
    exec_properties = {"gpu": "H20"},
    tags = ["manual"],
)
